TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Models/ModelosBD/Pai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TrabalhoPraticoPWeb1718.Models.ModelosBD
{
    public class Pai
    {
        public Pai()
        {
            Criancas = new HashSet<Crianca>();
        }
        public int PaiId { get; set; }
        public string Nome { get; set; }
        public string Cidade { get; set; }
        public string Contacto { get; set; }
        public string Nacionalidade { get; set; }


        public virtual ICollection<Crianca> Criancas { get; set; }
    }
}

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Models/ModelosBD/Pedidos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrabalhoPraticoPWeb1718.Models.ModelosBD
{
    public class Pedidos
    {
        public int PedidosId { get; set; }
        [Display(Name = "Pai/Mãe")]
        public int PaiId { get; set; }
        [Display(Name = "Instituição")]
        public int InstituicaoId { get; set; }

        [Display(Name = "Mensagem do Pai/Mãe")]
        public string MsgPai { get; set; }
        [Display(Name = "Mensagem da Instituição")]
        public string MsgInstituicao { get; set; }
    }
}

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Controllers/Controladores/PaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabalhoPraticoPWeb1718.Models;
using TrabalhoPraticoPWeb1718.Models.ModelosBD;
using TrabalhoPraticoPWeb1718.Models.Perfis;
using TrabalhoPraticoPWeb1718.Models.ViewModels;

namespace TrabalhoPraticoPWeb1718.Controllers.Controladores
{
    [Authorize(Roles = Perfis.Admin + "," + Perfis.Pai)]
    public class PaisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private const string UTILIZADOR = "UTILIZADOR";

        public ActionResult Index()
        {
            ViewBag.Utilizador = Session[UTILIZADOR];
            return View();
        }

        public ActionResult Create()
        {
            return View(GetListaInstituicoes(new PaisAutorizacaoViewModel()));
        }
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "ListaInstituicoes, ListaCidades")]PaisAutorizacaoViewModel pavm)
        {
            if (ModelState.IsValid)
            {
                PaiAutorizacao p = new PaiAutorizacao
                {
                    Nome = pavm.Nome,
                    Nacionalidade = pavm.Nacionalidade,
                    Contacto = pavm.Contacto,
                };
                p.IdInstituicaoPreencher = pavm.IdInstituicaoPreencher;
                p.Cidade = pavm.Cidade;

                db.PaisAutorizacao.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(GetListaInstituicoes(new PaisAutorizacaoViewModel()));
        }
        [NonAction]
        public PaisAutorizacaoViewModel GetListaInstituicoes(PaisAutorizacaoViewModel pavm)
        {
            List<SelectListItem> lista = new List<SelectListItem>();
            List<SelectListItem> cidades = new List<SelectListItem>();

            foreach (Instituicao ss in db.Instituicoes)
                lista.Add(new SelectListItem { Value = ss.InstituicaoId.ToString(), Text = ss.Nome });
            foreach (string ss in Distritos.GetListaDistritos())
                cidades.Add(new SelectListItem { Value = ss, Text = ss });

            SelectList s = new SelectList(lista, "Value", "Text");
            SelectList d = new SelectList(cidades, "Value", "Text");
            pavm.ListaInstituicoes = s;
            pavm.ListaCidades = d;
            return pavm;
        }

        public ActionResult ListaInstituicoes(InstituicoesCidadesVM c)
        {
            if (ViewBag.LISTA == null)
            {
                List<SelectListItem> distritos = new List<SelectListItem>();
                distritos.Add(new SelectListItem { Value = (-1).ToString(), Text = "Todas as Cidades" });
                foreach (var i in Models.Perfis.Distritos.GetListaDistritos())
                    distritos.Add(new SelectListItem { Value = i, Text = i });
                SelectList s = new SelectList(distritos, "Value", "Text");
                ViewBag.LISTA = s;
            }

            if (Request.IsAjaxRequest())
            {
                if (c.Opcao == "-1")
                    return PartialView("_Listar", db.Instituicoes.ToList());
                var cc = (from e in db.Instituicoes where e.Cidade == c.Opcao select e).ToList();
                return PartialView("_Listar", cc);
            }
            return View(new InstituicoesCidadesVM { InstituicoesLista = db.Instituicoes.ToList() });
        }

        public ActionResult ListaPais()
        {
            return View(db.Pais.ToList());
        }
        public ActionResult Entrar(int id)
        {
            Pai p = db.Pais.Find(id);
            if (p == null)
                throw new Exception("PAIS - Erro ao entrar como este pai");
            Session[UTILIZADOR] = p.Nome;
            return RedirectToAction("Index");
        }
        public ActionResult Sair()
        {
            Session[UTILIZADOR] = null;
            return RedirectToAction("Index");
        }


        public ActionResult ListaFilhos()
        {
            string s = (Session[UTILIZADOR] as string);
            Pai pai = (from i in db.Pais where i.Nome == s select i).ToList()[0];
            return View(pai.Criancas.ToList());
        }
        public JsonResult ObtemEnsinos(string ID)
        {
            if (ID == null)
                throw new Exception("Id = null");
            int id = Int32.Parse(ID);
            Instituicao inst = (from i in db.Instituicoes where i.InstituicaoId == id select i).ToList()[0];
            if (inst == null)
                throw new Exception("Instituicao nao existe");
            var t = (from e in db.Ensinos
                    where e.Instituicoes.Any(i => i.InstituicaoId == inst.InstituicaoId)
                    select new { e.EnsinoId, e.Nome}).ToList();
            return Json(t, JsonRequestBehavior.AllowGet);
        }
        public ActionResult CreateFilho()
        {
            ViewBag.Utilizador = Session[UTILIZADOR] as string;

            List<SelectListItem> l = new List<SelectListItem>();
            ViewBag.Ensinos = new SelectList(l, "Value", "Text");
            return View(AdicionaListas(new CriancasPaisInsituicaoEnsinoVM() { DataNascimento = DateTime.Now }));
        }
        [HttpPost]
        public ActionResult CreateFilho([Bind(Exclude = "ListaPais, ListaInstituicoes, Avaliacao, DataContrato")]CriancasPaisInsituicaoEnsinoVM cpievm)
        {
            if (ModelState.IsValid)
            {
                var c = new Crianca
                {
                    Nome = cpievm.Nome,
                    Avaliacao = -1,
                    DataContrato = DateTime.Now,
                    DataNascimento = cpievm.DataNascimento,
                    Genero = cpievm.Genero,
                };

                string utilizador = Session[UTILIZADOR] as string;
                if (utilizador == null)
                    throw new Exception("PAIS - Pai não tem a conta activada");

                var idI = Int32.Parse(cpievm.Instituicao);
                var idE = Int32.Parse(cpievm.OpcaoEnsino);
                Pai pp = (from procura in db.Pais where procura.Nome == utilizador select procura).ToList()[0];
                Instituicao ii = db.Instituicoes.Find(idI);
                Ensino e = (from ensinos in db.Ensinos where ensinos.EnsinoId == idE select ensinos).ToList()[0];
                if (pp == null || ii == null || e == null)
                    throw new Exception("PAIS - Pai ou Instituicao nao existem!");
                //var e = ii.Ensinos.ToList()[0];

                pp.Criancas.Add(c);
                ii.Criancas.Add(c);
                e.Criancas.Add(c);

                c.Pai = pp;
                c.Instituicao = ii;
                c.Ensino = e;

                db.Criancas.Add(c);
                db.SaveChanges();

                return RedirectToAction("ListaFilhos");
            }
            List<SelectListItem> l = new List<SelectListItem>();
            ViewBag.Ensinos = new SelectList(l, "Value", "Text");
            return View(AdicionaListas(cpievm));
        }
        [NonAction]
        public CriancasPaisInsituicaoEnsinoVM AdicionaListas(CriancasPaisInsituicaoEnsinoVM c)
        {
            List<SelectListItem> instituicoes = new List<SelectListItem>();
            foreach (Instituicao i in db.Instituicoes)
                instituicoes.Add(new SelectListItem { Value = i.InstituicaoId.ToString(), Text = i.Nome });

            SelectList si = new SelectList(instituicoes, "Value", "Text");

            c.ListaInstituicoes = si;
            return c;
        }

        public ActionResult AvaliarInstituicao(int id)
        {
            var f = new AvaliacaoVM { Filho = id.ToString() };
            return View(f);
        }
        [HttpPost]
        public ActionResult AvaliarInstituicao(AvaliacaoVM a)
        {
            if (ModelState.IsValid)
            {
                if (a.Avaliacao >= 0 && a.Avaliacao <= 20)
                {
                    int idd = Int32.Parse(a.Filho);
                    Crianca c = db.Criancas.Find(idd);
                    if (c == null)
                        throw new Exception("PAIS - Alguem apagou este filho!");
                    c.Avaliacao = a.Avaliacao;
                    db.SaveChanges();
                    return RedirectToAction("ListaFilhos");
                }
            }
            return View(a);
        }
        public ActionResult Pedidos()
        {
            string paiNome = Session[UTILIZADOR] as string;
            Pai p = (from i in db.Pais where i.Nome == paiNome select i).ToList()[0];

            if (p == null)
                throw new Exception("PAIS - este pai não existe");

            List<Pedidos> pedidos = (from s in db.Pedidos where s.PaiId == p.PaiId select s).ToList();
            return View(pedidos);
        }
        public ActionResult FazerPedido()
        {
            List<SelectListItem> l = new List<SelectListItem>();
            foreach (var i in db.Instituicoes)
                l.Add(new SelectListItem { Value = i.InstituicaoId.ToString(), Text = i.Nome });

            SelectList s = new SelectList(l, "Value", "Text");
            return View(new PedidosCliente { ListaIntituicoes = s });
        }
        [HttpPost]
        public ActionResult FazerPedido([Bind(Exclude = "ListaInstituicoes")]PedidosCliente pc)
        {
            if (ModelState.IsValid)
            {
                string paiNome = Session[UTILIZADOR] as string;
                Pai p = (from i in db.Pais where i.Nome == paiNome select i).ToList()[0];

                if (p == null)
                    throw new Exception("PAIS - este pai não existe");

                var idInst = Int32.Parse(pc.OpcaoInstituicao);
                db.Pedidos.Add(new Pedidos { MsgPai = pc.Mensagem, InstituicaoId = idInst, PaiId = p.PaiId, MsgInstituicao = "" });
                db.SaveChanges();

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/AddServicos.cshtml
@model TrabalhoPraticoPWeb1718.Models.ViewModels.InstituicaoAddServicosVM

@{
    ViewBag.Title = "INSTITUIÇÕES - Adicionar Servicos";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OpcaoServicos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.OpcaoServicos, Model.ListaServicos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpcaoServicos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar Serviço" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a INSTITUIÇÕES Adicionar Serviços", "ListaServicos")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/Avaliacao.cshtml
@model IEnumerable<TrabalhoPraticoPWeb1718.Models.ModelosBD.Crianca>

@{
    ViewBag.Title = "Avaliação da Instituição " + ViewBag.Instituicao;
}

<h2>@ViewBag.Title</h2>
<img src="~/Content/Imagens/rating.jpg" width="400" height="130" class="img-responsive"/>
<br />
@{
    double media = 0, elementos = 0;

    foreach (var i in Model)
    {
        if (i.Avaliacao != null && i.Avaliacao != -1)
        {
            media += (double)i.Avaliacao.Value;
            elementos++;
        }
    }
    media /= elementos;
    if (elementos != 0)
    {
        <h4>A média da instituição @ViewBag.Instituicao é de @media Valores</h4>
    }
    else
    {
        <h4>A sua instituição ainda não foi avaliada</h4>
    }
}
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.Label("Avaliação")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @{
                string s = item.Avaliacao.ToString() + " Valores";
                if (item.Avaliacao == -1)
                {
                    @Html.Label("Por avaliar")
                }
                else if (item.Avaliacao < 10)
                {
                    @Html.Label(s, new { @class = "text-danger"} )
                }
                else if (item.Avaliacao >= 10 && item.Avaliacao < 15)
                {
                    @Html.Label(s, new { @class = "text-warning" })
                }
                else
                {
                    @Html.Label(s, new { @class = "text-success" })
                }
            }
        </td>
    </tr>
}

</table>
@Html.ActionLink("Voltar a INSTITUIÇÕES", "Index")

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/Create.cshtml
@model TrabalhoPraticoPWeb1718.Models.ViewModels.InstituicoesAutorizacaoViewModel

@{
    ViewBag.Title = "INSTITUIÇÕES - Criar conta Instituição";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroProfessores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroProfessores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroProfessores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cidade, Model.ListaCidades, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contacto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contacto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contacto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoInstituicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoInstituicao, Model.ListaTipoInstituicoes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoInstituicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Servico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Servico, Model.ListaEnsinos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Servico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensalidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mensalidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mensalidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar conta" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a INSTITUIÇÕES", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/Index.cshtml
@{
    ViewBag.Title = "INSTITUIÇÕES - Índice";
}

<h2>@ViewBag.Title</h2>
@{
    if (ViewBag.UTILIZADOR != null)
    {
        <h3>Conta: @((string)ViewBag.Utilizador) | @Html.ActionLink("Terminar Sessão", "Sair", null, new { @class = "text-warning" })</h3>
    }
}
<img src="~/Content/Imagens/3.jpg"  width="500" height="500" class="img-responsive" />

<dl>
    @{
        if (ViewBag.UTILIZADOR != null)
        {
            <dt>@Html.ActionLink("Entrar com outra conta INSTITUIÇÃO", "List")</dt>
            <dd>- Mostra todas os pais inscritos</dd>
        }
        else
        {
            <dt>@Html.ActionLink("Entrar com uma conta INSTITUIÇÃO", "List")</dt>
            <dd>- Mostra todas os pais inscritos</dd>
        }
    }
    @{
        if (ViewBag.UTILIZADOR == null)
        {
            <dt>@Html.ActionLink("Criar uma conta INSTITUIÇÃO", "Create")</dt>
            <dd>- Crie uma conta antes de tentar registar os serviços por si disponibilizados</dd>
        }
    } 
    @{
        if (ViewBag.UTILIZADOR != null)
        {
            <dt>@Html.ActionLink("As avaliações da minha instituição", "Avaliacao")</dt>
            <dd>- Lista todos os alunos que me avaliaram</dd>
            <dt>@Html.ActionLink("Adicionar mais serviços", "ListaServicos")</dt>
                <dd>- Lista de todos as instituições inscritas no Spaces for children</dd>
                <dt>@Html.ActionLink("Alunos inscritos", "ListaAlunos")</dt>
                <dd>- Lista de todos as instituições inscritas no Spaces for children</dd>
                <dt>@Html.ActionLink("Autorizar pais", "Pais")</dt>
                <dd>- Lista de todos as instituições inscritas no Spaces for children</dd>
                <dt>@Html.ActionLink("Responder a Pedidos", "Pedidos")</dt>
                <dd>- Lista de todos as instituições inscritas no Spaces for children</dd>
        }
    } 
</dl>

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/List.cshtml
@model IEnumerable<TrabalhoPraticoPWeb1718.Models.ModelosBD.Instituicao>

@{
    ViewBag.Title = "INSTITUIÇÕES - Lista de Instituições";
}

<h2>@ViewBag.Title</h2>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.Label("Número de professores")
        </th>
        <th>
            @Html.Label("Distrito")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contacto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th>
        <th>
            @Html.Label("Tipo de Instituição")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mensalidade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumeroProfessores)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contacto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoInstituicao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mensalidade)
        </td>
        <td>
            @Html.ActionLink("Entrar como esta Instituição", "Entrar", new { id = item.InstituicaoId }, new { @class = "text-sucess"} )
        </td>
    </tr>
}

</table>

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/ListaAlunos.cshtml
@model IEnumerable<TrabalhoPraticoPWeb1718.Models.ModelosBD.Crianca>

@{
    ViewBag.Title = "Lista de Alunos da Instituição " + ((string)ViewBag.Instituicao);
}

<h2>@ViewBag.Title</h2>
<img src="~/Content/Imagens/estudantes.jpg" width="650" height="400" class="img-responsive"/>
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.Label("Género")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.Label("Data do contrato")
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @{
                if (item.Genero == TrabalhoPraticoPWeb1718.Models.ModelosBD.Genero.Masculino)
                {
                    <img src="~/Content/Imagens/rapaz.png" width="50" height="50" />
                }
                else
                {
                    <img src="~/Content/Imagens/rapariga.png" width="50" height="50" />
                }
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataContrato)
        </td>

        <td></td>
    </tr>
}

</table>
@Html.ActionLink("Voltar a INSTITUIÇÕES", "Index")

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/ListaServicos.cshtml
@model IEnumerable<TrabalhoPraticoPWeb1718.Models.ModelosBD.Ensino>

@{
    ViewBag.Title = "Lista de Servicos da Instituição " + ViewBag.Instituicao;
}

<h2>@ViewBag.Title</h2>
<img src="~/Content/Imagens/servicos.png" width="500" height="200" class="img-responsive"/>
<br />
<p>
    @Html.ActionLink("Adicionar mais serviços", "AddServicos")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
        </tr>
}

</table>
@Html.ActionLink("Voltar a INSTITUIÇÕES", "Index")

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/Pais.cshtml
@model IEnumerable<TrabalhoPraticoPWeb1718.Models.ModelosBD.PaiAutorizacao>

@{
    ViewBag.Title = "INSTITUIÇÕES - Autorizar Pais";
}

<h2>@ViewBag.Title</h2>
<img src="~/Content/Imagens/lock.png" width="140" height="200", class="img-responsive"/>
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contacto)
        </th>
        <th>
            @Html.Label("Naturalidade")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contacto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nacionalidade)
        </td>
        <td>
            @Html.ActionLink("Autoriza Pai/Mãe", "AutorizaPai", new { id=item.PaiAutorizacaoId }, new { @class="text-success"})
        </td>
    </tr>
}

</table>
@Html.ActionLink("Voltar a INSTITUIÇÕES", "Index")

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Instituicoes/ResponderPedido.cshtml
@model TrabalhoPraticoPWeb1718.Models.ViewModels.PedidosInstituicao

@{
    ViewBag.Title = "Responder a Pedido";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPedido)

        <div class="form-group">
            @Html.LabelFor(model => model.Mensagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mensagem, 5, 100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mensagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Responder" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a Pedidos", "Pedidos")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}