TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Controllers/Controladores/InstituicoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabalhoPraticoPWeb1718.Models;
using TrabalhoPraticoPWeb1718.Models.ModelosBD;
using TrabalhoPraticoPWeb1718.Models.Perfis;
using TrabalhoPraticoPWeb1718.Models.ViewModels;

namespace TrabalhoPraticoPWeb1718.Controllers.Controladores
{
    [Authorize(Roles = Perfis.Admin + "," + Perfis.Instituicao)]
    public class InstituicoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private const string INSTITUICAO_UTILIZADOR = "INSTITUICAO_UTILIZADOR";

        public ActionResult Index()
        {
            ViewBag.Utilizador = Session[INSTITUICAO_UTILIZADOR];
            return View();
        }
        public ActionResult ListaAlunos()
        {
            string nomeInstituicao = Session[INSTITUICAO_UTILIZADOR] as string;
            ViewBag.Instituicao = nomeInstituicao;
            if (nomeInstituicao == null)
                throw new Exception("INSTITUICOES - Nenhuma instituicao está activada!");
            Instituicao i = (from e in db.Instituicoes where e.Nome == nomeInstituicao select e).ToList()[0];
            return View(i.Criancas.ToList());
        }


        public ActionResult Create()
        {
            return View(AdicionaListas(new InstituicoesAutorizacaoViewModel()));
        }
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "listaDistritos, listaEnsinos, listaTipoInstituicoes")]InstituicoesAutorizacaoViewModel iavm)
        {
            if (ModelState.IsValid)
            {
                var instituicao = new InstituicaoAutorizacao
                {
                    Nome = iavm.Nome,
                    Contacto = iavm.Contacto,
                    Fax = iavm.Fax,
                    NumeroProfessores = iavm.NumeroProfessores,
                    TipoInstituicao = iavm.TipoInstituicao,
                    Cidade = iavm.Cidade,
                    Mensalidade = iavm.Mensalidade
                };
                int id = Int32.Parse(iavm.Servico);
                Ensino e = db.Ensinos.Find(id);
                if (e == null)
                    throw new Exception("Este tipo de Serviço não existe!");
                instituicao.Servico = e.EnsinoId.ToString();

                db.InstituicoesAutorizacao.Add(instituicao);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(iavm);
        }
        [NonAction]
        public InstituicoesAutorizacaoViewModel AdicionaListas(InstituicoesAutorizacaoViewModel iavm)
        {
            List<string> distritos = Distritos.GetListaDistritos();
            List<SelectListItem> listaDistritos = new List<SelectListItem>();
            List<SelectListItem> listaEnsinos = new List<SelectListItem>();
            List<SelectListItem> listaTipoInstituicoes = new List<SelectListItem>()
            {
                new SelectListItem { Value = "Privada", Text = "Privada"},
                new SelectListItem { Value = "Pública", Text = "Pública"},
                new SelectListItem { Value = "IPSS", Text = "IPSS"}
            };

            foreach (string s in distritos)
                listaDistritos.Add(new SelectListItem { Value = s, Text = s });
            foreach (Ensino s in db.Ensinos.ToList())
                listaEnsinos.Add(new SelectListItem { Value = s.EnsinoId.ToString(), Text = s.Nome });

            SelectList s1 = new SelectList(listaDistritos, "Value", "Text");
            SelectList s2 = new SelectList(listaEnsinos, "Value", "Text");
            SelectList s3 = new SelectList(listaTipoInstituicoes, "Value", "Text");

            iavm.ListaCidades = s1;
            iavm.ListaEnsinos = s2;
            iavm.ListaTipoInstituicoes = s3;

            return iavm;
        }


        public ActionResult List()
        {
            return View(db.Instituicoes.ToList());
        }

        public ActionResult Pais()
        {
            return View(db.PaisAutorizacao.ToList());
        }
        public ActionResult AutorizaPai(int id)
        {
            var pa = db.PaisAutorizacao.Find(id);
            var p = new Pai
            {
                Cidade = pa.Cidade,
                Nome = pa.Nome,
                Contacto = pa.Contacto,
                Nacionalidade = pa.Nacionalidade
            };

            db.PaisAutorizacao.Remove(pa);
            db.Pais.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Avaliacao()
        {
            string nomeInstituicao = Session[INSTITUICAO_UTILIZADOR] as string;
            ViewBag.Instituicao = nomeInstituicao;
            if (nomeInstituicao == null)
                throw new Exception("INSTITUICOES - Nenhuma instituicao está activada!");
            Instituicao i = (from e in db.Instituicoes where e.Nome == nomeInstituicao select e).ToList()[0];
            return View(i.Criancas.ToList());
        }

        public ActionResult AddServicos()
        {
            string nomeInstituicao = Session[INSTITUICAO_UTILIZADOR] as string;
            ViewBag.Instituicao = nomeInstituicao;
            if (nomeInstituicao == null)
                throw new Exception("INSTITUICOES - Nenhuma instituicao está activada!");
            Instituicao i = (from e in db.Instituicoes where e.Nome == nomeInstituicao select e).ToList()[0];

            List<SelectListItem> listaServicos = new List<SelectListItem>();
            foreach (var a in db.Ensinos)
                listaServicos.Add(new SelectListItem { Value = a.EnsinoId.ToString(), Text = a.Nome });

            SelectList s = new SelectList(listaServicos, "Value", "Text");
            var serv = new InstituicaoAddServicosVM { ListaServicos = s };

            return View(serv);
        }
        [HttpPost]
        public ActionResult AddServicos([Bind(Exclude = "ListaServicos")] InstituicaoAddServicosVM modelo)
        {
            string nomeInstituicao = Session[INSTITUICAO_UTILIZADOR] as string;
            ViewBag.Instituicao = nomeInstituicao;
            if (nomeInstituicao == null)
                throw new Exception("INSTITUICOES - Nenhuma instituicao está activada!");
            Instituicao i = (from e in db.Instituicoes where e.Nome == nomeInstituicao select e).ToList()[0];

            if (ModelState.IsValid)
            {
                int id = Int32.Parse(modelo.OpcaoServicos);
                Ensino e = db.Ensinos.Find(id);
                if (!i.Ensinos.Contains(e))
                {
                    e.Instituicoes.Add(i);
                    i.Ensinos.Add(e);
                    db.SaveChanges();
                }
                return RedirectToAction("ListaServicos");
            }
            List<SelectListItem> listaServicos = new List<SelectListItem>();
            foreach (var a in db.Ensinos)
                listaServicos.Add(new SelectListItem { Value = a.EnsinoId.ToString(), Text = a.Nome });

            SelectList s = new SelectList(listaServicos, "Value", "Text");
            return View(modelo);
        }


        public ActionResult ListaServicos()
        {
            string nomeInstituicao = Session[INSTITUICAO_UTILIZADOR] as string;
            ViewBag.Instituicao = nomeInstituicao;
            if (nomeInstituicao == null)
                throw new Exception("INSTITUICOES - Nenhuma instituicao está activada!");
            Instituicao i = (from e in db.Instituicoes where e.Nome == nomeInstituicao select e).ToList()[0];

            return View(i.Ensinos.ToList());
        }

        public ActionResult Pedidos()
        {
            var instituicaoNome = Session[INSTITUICAO_UTILIZADOR] as string;
            Instituicao i = (from e in db.Instituicoes where e.Nome == instituicaoNome select e).ToList()[0];
            if (i == null)
                throw new Exception("Pedidos");

            return View((from s in db.Pedidos where s.InstituicaoId == i.InstituicaoId select s).ToList());
        }
        public ActionResult ResponderPedido(int id)
        {
            return View(new PedidosInstituicao { IdPedido = id });
        }
        [HttpPost]
        public ActionResult ResponderPedido(PedidosInstituicao pc)
        {
            if (ModelState.IsValid)
            {
                Pedidos p = db.Pedidos.Find(pc.IdPedido);
                p.MsgInstituicao = pc.Mensagem;
                db.SaveChanges();
                return RedirectToAction("Pedidos");
            }
            return View(pc);
        }


        public ActionResult Entrar(int id)
        {
            Instituicao i = db.Instituicoes.Find(id);
            if (i == null)
                throw new Exception("INSTITUICOES - Erro ao entrar como esta Instituicao");
            Session[INSTITUICAO_UTILIZADOR] = i.Nome;
            return RedirectToAction("Index");
        }
        public ActionResult Sair()
        {
            Session[INSTITUICAO_UTILIZADOR] = null;
            return RedirectToAction("Index");
        }

        public JsonResult ValidarInstituicaoNome(string Nome)
        {
            bool existe = false;
            foreach (Instituicao i in db.Instituicoes)
            {
                if (i.Nome == Nome)
                {
                    existe = true;
                    break;
                }
            }
            return Json(!existe, JsonRequestBehavior.AllowGet);
        }
    }
}

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "ADMINISTRADOR - Índice";
}

<h2>@ViewBag.Title</h2>
<img src="~/Content/Imagens/4.jpg"  width="500" height="500" class="img-responsive" />

<dl>
    <dt>@Html.ActionLink("Autorizar Instituições", "Instituicoes")</dt>
    <dd>- As instituições deverão ser activadas por si</dd>
    <dt>@Html.ActionLink("Alterar tabela Pais", "Index", "PaisHidden")</dt>
    <dd>- Modificar valores da tabela Pais</dd>
    <dt>@Html.ActionLink("Alterar tabela Crianças", "Index", "CriancasHidden")</dt>
    <dd>- Modificar valores da tabela Crianças</dd>
    <dt>@Html.ActionLink("Alterar tabela Instituições", "Index", "InstituicoesHidden")</dt>
    <dd>- Modificar valores da tabela Instituições</dd>
    <dt>@Html.ActionLink("Alterar tabela Ensinos", "Index", "EnsinosHidden")</dt>
    <dd>- Modificar valores da tabela Ensinos</dd>
    <dt>@Html.ActionLink("Alterar tabela Disciplinas", "Index", "DisciplinasHidden")</dt>
    <dd>- Modificar valores da tabela Disciplinas</dd>
</dl>

TrabalhoPraticoPWeb1718/TrabalhoPraticoPWeb1718/Views/Admin/Instituicoes.cshtml
@model IEnumerable<TrabalhoPraticoPWeb1718.Models.ModelosBD.InstituicaoAutorizacao>

@{
    ViewBag.Title = "Autorizar Instituicoes";
}

<h2>@ViewBag.Title</h2>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.Label("Número de professores")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contacto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th>
        <th>
            @Html.Label("Tipo de Instituição")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mensalidade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumeroProfessores)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contacto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoInstituicao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mensalidade)
        </td>
        <td>
            @Html.ActionLink("Autorizar Instituicao", "AutorizaInstituicao", new { id=item.InstituicaoAutorizacaoId}, new { @class = "text-success" })
        </td>
    </tr>
}

</table>
@Html.ActionLink("Voltar para ADMINSTRADOR", "Index")